if(NOT DEFINED PKGS_PATH)
    set(PKGS_PATH /home/usergrp/data/pkgs)
endif()

message(STATUS "PKGS_PATH: ${PKGS_PATH}")

set(BOOST_PATH ${PKGS_PATH}/boost)
set(SPDLOG_PATH ${PKGS_PATH}/spdlog)
set(LIBHV_PATH ${PKGS_PATH}/hv)
set(PYBIND11_PATH ${PKGS_PATH}/hv)

list(APPEND CMAKE_PREFIX_PATH ${BOOST_PATH})
list(APPEND CMAKE_PREFIX_PATH ${SPDLOG_PATH})
list(APPEND CMAKE_PREFIX_PATH ${LIBHV_PATH})
list(APPEND CMAKE_PREFIX_PATH ${PYBIND11_PATH})

message(STATUS "CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
